workflows:
  # The following workflow is for generating a debug build
  debug-workflow: # workflow ID
    name: Native Android # workflow name
    max_build_duration: 60 # max build duration in minutes
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # build debug apk
        ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - gilromeu.p@gmail.com # enter your email id her