# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gerando Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build_Release_AAB:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      
    - name: Build Release AAB
      run: ./gradlew bundleProduction

    - name: Read value from Properties-versionName
      id: read_property
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: 'versionName.properties'
        property: 'versionName'
    - name: Release Version
      run: echo ${{ steps.read_property.outputs.value }}

    - name: Sign AAB
      id: sign_app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/productionRelease
        signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

    - name: Rename AAB
      run: mv ${{steps.sign_app.outputs.signedReleaseFile}} "v${{ steps.read_property.outputs.value }}.aab"

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.read_property.outputs.value }}
        path: "v${{ steps.read_property.outputs.value }}.aab"

  Build_Release_APK:

    runs-on: ubuntu-latest
    needs: Build_Release_AAB
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      
    - name: Build Release APK
      run: ./gradlew assembleProduction

    - name: Read value from Properties-versionName
      id: read_property
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: 'versionName.properties'
        property: 'versionName'
    - name: Release Version
      run: echo ${{ steps.read_property.outputs.value }}

    - name: Sign APK
      id: sign_app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/production/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

    - name: Versao
      run: echo ${{steps.sign_app.outputs.signedReleaseFile}}

    - name: Rename AAB
      run: mv ${{steps.sign_app.outputs.signedReleaseFile}} 'v${{ steps.read_property.outputs.value }}.apk'

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.read_property.outputs.value }}
        path: "v${{ steps.read_property.outputs.value }}.apk"
