# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gerando Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - id: step1
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      
    - name: Build Release AAB
      run: ./gradlew bundleRelease 
      
   # - name: Build Release APK
   #   run: ./gradlew assembleRelease 

  sign:
    runs-on: ubuntu-latest
    steps:
      - id: step1
      - uses: actions/checkout@v2

      - name: Sign AAB
      - uses: r0adkll/sign-android-release@v1     
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}
        
 # upload:
  
     # runs-on: ubuntu-latest
    
     # steps:
       # - uses: actions/upload-artifact@v3
        #  with:
          #  name: v1.0
           # path: app/build/outputs/bundle/release/*.aab
