name: Build Release App Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:    
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Generate Release APK
      run: ./gradlew bundleRelease && ./gradlew assembleRelease
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: |
          app/build/outputs/apk/release/.*apk
          app/build/outputs/bundle/release/.*aab
        signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "30.0.2"
